import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Ahmed Rizk',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Khaled Hamdy',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Agenda-Wired',
      slug: 'agenda-wired',
      type: 'agenda',
      description: 'Stylish agenda for everyday use',
      category: 'agendas',
      image: '/images/Agenda-Wired-Dreamcatcher.png',
      style: 'wired',
      design: 'Dream Catcher',
      price: '135',
      brand: 'local',
      rating: 4.5,
      numReviews: 13,
      countInStock: 23,
      fullDescription:
        'Organize your life, set goals, and get things done with our stylish 2021 - 2022 wired agendas that make planning--and succeeding--fun and easy.',
    },
    {
      name: 'Agenda-Bookstyle',
      slug: 'agenda-bookstyle',
      type: 'agenda',
      description: 'Stylish agenda for everyday use',
      category: 'agendas',
      image: '/images/Agenda-Bookstyle-Friends.jpeg',
      style: 'bookstyle',
      design: 'Friends',
      price: '135',
      brand: 'local',
      rating: 3.5,
      numReviews: 2,
      countInStock: 7,
      fullDescription:
        'Organize your life, set goals, and get things done with our stylish 2021 - 2022 wired agendas that make planning--and succeeding--fun and easy.',
    },
    {
      name: 'Blue Jeans Bag',
      slug: 'blue-jeans-bag',
      type: 'bag',
      description: 'Shoulder blue jeans tote.',
      category: 'bags',
      image: '/images/Blue Jeans bag-Customize.jpeg',
      style: 'Jeans',
      design: 'Customize',
      price: '190',
      brand: 'local',
      rating: 5.0,
      numReviews: 53,
      countInStock: 15,
      fullDescription:
        'Shoulder blue jeans bag with a modern twist: Print allows for 100% customization, bringing the basic tote to the next level.',
    },
    {
      name: 'Can-Stainless Steel',
      slug: 'can-stainless',
      type: 'can',
      description: 'Made of unbreakable stainless steel.',
      category: 'cans',
      image: '/images/Can-Stainless Steel-Ready.png',
      style: 'general',
      design: 'c',
      price: '170',
      brand: 'local',
      rating: 4.0,
      numReviews: 3,
      countInStock: 9,
      fullDescription:
        'White Custom Printed Cola Can Vacuum Flask Thermo Bottle, Size: 330 mL',
    },
    {
      name: 'Touch-Lamp',
      slug: 'touch-lamp',
      type: 'speaker',
      description: 'Bluetooth speaker with touch led lamp.',
      category: 'accessories',
      image: '/images/Touch-Lamp speaker.jpeg',
      style: 'general',
      design: 'Customize',
      price: '140',
      brand: 'local',
      rating: 5.0,
      numReviews: 35,
      countInStock: 8,
      fullDescription:
        'Bluetooth Speaker Table Lamp with Mood Light . METAL HANDLE AND HOOK The portable speakers come with a sturdy metal handle which can help you hang the lights in case of hiking or camping or outdoor events.',
    },
    {
      name: 'Square Cushion-Cottons Duck',
      slug: 'square-cushion-cottons-duck',
      type: 'cushion',
      description: 'Printed Square Cushion Cotton.',
      category: 'cushions',
      image: '/images/Square Cushion-Cottons Duck -Off-White Duck-Ready.jpeg',
      style: 'cotton-duck',
      design: 'Off',
      price: '150',
      brand: 'local',
      rating: 5.0,
      numReviews: 30,
      countInStock: 19,
      fullDescription:
        'Change the look of your living room and fetch compliments from your guests with this modern cushion. The print and tones are sure to grab attention while the soft material makes it a lovely pick.',
    },
  ],
};

export default data;
